export { http } from './http.js'
export * as authApi from './auth.js'
export * as catalogApi from './catalog.js'
export * as designApi from './design.js'
export * as orderApi from './order.js'
export * as aiApi from './ai.js'
export { imageProxyUrl, parseAiResultUrl } from './ai.js'
export * as userApi from './user.js'
export * as uploadApi from './upload.js'
export * as configApi from './config.js'

// 类型导出（供页面/组件复用）
export type { CreateOrderInput, PrepayResult, Shipment, PriceBreakdown, OrderAttachment } from './order.js'
export type { StreamChatTurn, StreamChatPayload, StreamChatHandlers, StreamChatHandle } from './ai.js'
export type { SaveDesignInput } from './design.js'
export type { VariantRecipe, VariantColors, VariantParams } from './ai.js'
export type { Article, Banner, Tag } from './catalog.js'
export type { UploadResult } from './upload.js'
export type { HomeConfig, ConfigItem } from './config.js'
