/**
 * pageMeta — 18 页元数据配置
 * 每页包含: title, role, isTab, summary, modules, rules, links
 */

export const PAGE_META = {
  // ========== C 端 · 消费者 (9 页) ==========
  'c-home': {
    key: 'c-home',
    no: '01',
    title: '商城首页',
    role: 'consumer',
    isTab: true,
    tabLabel: '商城',
    parentTab: 'c-home',
    summary: '消费者进入小程序的第一屏。banner 主推活动，下方推荐款 + 分类入口。',
    modules: ['顶部 banner 轮播', '横向品类滚动', '热销 4 列网格', 'AI 灵感入口'],
    rules: ['未登录可浏览', '加购需登录', '推荐数据接 /api/products/featured'],
    links: ['c-category', 'c-detail', 'c-customize'],
  },
  'c-category': {
    key: 'c-category',
    no: '02',
    title: '分类列表',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-home',
    summary: '按品类筛选商品，支持价格/材质/库存筛选。',
    modules: ['顶部 4 个分类 tab', '筛选(价格/材质/库存)', '2 列瀑布流商品卡', '触底加载'],
    rules: ['默认按销量排序', '每页 20 条', '支持下拉刷新'],
    links: ['c-home', 'c-detail'],
  },
  'c-detail': {
    key: 'c-detail',
    no: '03',
    title: '单品详情',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-home',
    summary: '商品详情 + 规格选择，底部加购/立即定制。',
    modules: ['商品主图轮播', '价格 + 标签 + 销量', '尺码/颜色选择器', '详情描述 + 评价', '底部"加购"/"立即定制"'],
    rules: ['加购需选规格', '库存不足灰显', '定制跳转到定制页'],
    links: ['c-category', 'c-customize', 'c-cart'],
  },
  'c-customize': {
    key: 'c-customize',
    no: '04',
    title: '定制',
    role: 'consumer',
    isTab: true,
    tabLabel: '定制',
    parentTab: 'c-customize',
    summary: '轻量定制：套花型 + 改底色，实时预览。',
    modules: ['实时袜版预览(SVG)', '9 个花型横滑选择', '4 个底色快选', '"加购定制款"按钮'],
    rules: ['花型实时渲染', '底色支持自定义', '预览支持旋转'],
    links: ['c-cart', 'c-order'],
  },
  'c-cart': {
    key: 'c-cart',
    no: '05',
    title: '购物车',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-home',
    summary: '合并定制款 + 现货，统一结算。',
    modules: ['商品行(图/标题/规格/数量)', '定制款带"我的设计"标识', '底部总价 + 结算按钮', '左滑删除'],
    rules: ['定制款不可修改规格', '库存变动实时校验', '空购物车引导'],
    links: ['c-order'],
  },
  'c-order': {
    key: 'c-order',
    no: '06',
    title: '下单确认',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-home',
    summary: '地址 + 支付方式，确认下单。',
    modules: ['收货地址(可切换)', '订单明细折叠', '优惠券 / 备注', '支付方式(微信/支付宝)', '"提交订单"按钮'],
    rules: ['地址必填校验', '优惠券自动匹配', '提交后锁定库存 15 分钟'],
    links: ['c-pay-success'],
  },
  'c-pay-success': {
    key: 'c-pay-success',
    no: '07',
    title: '支付成功',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-home',
    summary: '下单后落地页，引导查看订单或继续逛。',
    modules: ['大对勾 + "支付成功"', '订单号 + 金额', '"查看订单"/"继续逛逛"'],
    rules: ['3 秒后自动跳转订单详情', '分享按钮可分享订单'],
    links: ['c-order-detail', 'c-home'],
  },
  'c-mine': {
    key: 'c-mine',
    no: '08',
    title: '我的',
    role: 'consumer',
    isTab: true,
    tabLabel: '我的',
    parentTab: 'c-mine',
    summary: '个人中心入口聚合，订单/收藏/地址/设置。',
    modules: ['头像 + 昵称 + 等级', '订单 4 状态入口', '收藏 / 地址 / 优惠券', '客服 / 设置'],
    rules: ['未登录显示登录引导', '订单数字角标实时更新'],
    links: ['c-order-detail'],
  },
  'c-order-detail': {
    key: 'c-order-detail',
    no: '09',
    title: '订单详情',
    role: 'consumer',
    isTab: false,
    parentTab: 'c-mine',
    summary: '订单状态 + 物流追踪，底部操作。',
    modules: ['状态步骤条', '商品列表', '地址 + 物流号', '价格明细', '底部操作(再次购买/售后)'],
    rules: ['物流信息实时拉取', '7 天内可申请售后', '已完成可评价'],
    links: ['c-mine'],
  },

  // ========== B 端 · 设计师 (9 页) ==========
  'b-workspace': {
    key: 'b-workspace',
    no: '10',
    title: '工作台',
    role: 'designer',
    isTab: true,
    tabLabel: '工作台',
    parentTab: 'b-workspace',
    summary: 'B 端首屏：数据卡 + 快捷入口 + 最近设计。',
    modules: ['4 个数据卡(今日订单/进行中/库存款/收入)', '"新建袜版"主 CTA', '最近设计 / 待办订单'],
    rules: ['数据每 5 分钟刷新', '新建跳转编辑器', '待办按紧急度排序'],
    links: ['b-editor', 'b-orders'],
  },
  'b-editor': {
    key: 'b-editor',
    no: '11',
    title: '编辑器',
    role: 'designer',
    isTab: true,
    tabLabel: '编辑器',
    parentTab: 'b-editor',
    summary: '移动版袜版编辑器（简化），四区填充 + 调参。',
    modules: ['袜版预览(SVG 四区填充)', '区域 tab(袜口/螺口/主体/袜头)', '花型横滑 + 印花上传', '密度/旋转/间距滑块', '底部按钮: AI 同款 / 亲子袜 / 下单'],
    rules: ['自动保存草稿', '花型支持缩放', '导出 PNG/SVG'],
    links: ['b-ai-extend', 'b-family', 'b-assets', 'b-submit'],
  },
  'b-ai-extend': {
    key: 'b-ai-extend',
    no: '12',
    title: 'AI 同款延伸',
    role: 'designer',
    isTab: false,
    parentTab: 'b-editor',
    summary: '基于当前设计生成 1/2/4 张同款变体。',
    modules: ['顶部"生成数量"切换(1/2/4)', '当前底图 thumbnail', '结果网格(loading 占位)', '点击单张 → 应用到画布'],
    rules: ['生成耗时 3-8 秒', '结果缓存 24 小时', '每日免费 10 次'],
    links: ['b-editor'],
  },
  'b-family': {
    key: 'b-family',
    no: '13',
    title: '亲子袜套装',
    role: 'designer',
    isTab: false,
    parentTab: 'b-editor',
    summary: '成人 + 儿童两版同款，支持比例调整。',
    modules: ['左右双袜预览', '"换比例"按钮', '分别下载 / 一起保存', '底部"保存套装"'],
    rules: ['儿童版自动缩放 70%', '花型密度自动适配', '套装绑定同一订单'],
    links: ['b-editor'],
  },
  'b-assets': {
    key: 'b-assets',
    no: '14',
    title: '素材库',
    role: 'designer',
    isTab: false,
    parentTab: 'b-editor',
    summary: '花型 + AI 生成 + 我上传，3 列网格管理。',
    modules: ['顶部 tab(内置/AI/我的)', '3 列网格，长按多选', '"AI 生成"FAB 按钮', '底部"应用到画布"'],
    rules: ['上传限制 5MB', '支持 PNG/SVG/JPG', 'AI 生成需描述词'],
    links: ['b-editor'],
  },
  'b-designs': {
    key: 'b-designs',
    no: '15',
    title: '我的设计',
    role: 'designer',
    isTab: true,
    tabLabel: '设计',
    parentTab: 'b-designs',
    summary: '设计稿网格视图，支持筛选和批量操作。',
    modules: ['顶部筛选(全部/草稿/已下单)', '2 列大图网格', '右上角时间/状态徽章', '长按多选 / 单击编辑'],
    rules: ['草稿 30 天自动清理', '已下单不可删除', '支持复制设计'],
    links: ['b-editor', 'b-submit'],
  },
  'b-submit': {
    key: 'b-submit',
    no: '16',
    title: '下单提交',
    role: 'designer',
    isTab: false,
    parentTab: 'b-designs',
    summary: 'B 端批量下单：尺码组合 + 材质 + 工艺。',
    modules: ['设计稿预览', '尺码组合表(S/M/L/XL 数量)', '材质 + 工艺选择', '收货地址', '备注 + 总价 + 提交'],
    rules: ['最低起订 50 双', '材质影响单价', '工艺影响工期'],
    links: ['b-designs', 'b-orders'],
  },
  'b-orders': {
    key: 'b-orders',
    no: '17',
    title: '订单管理',
    role: 'designer',
    isTab: true,
    tabLabel: '订单',
    parentTab: 'b-orders',
    summary: '订单状态列表，支持筛选和下拉刷新。',
    modules: ['状态 tab(全部/待生产/生产中/已发货/已完成)', '订单卡(订单号/设计图/状态/时间)', '下拉刷新 + 触底加载'],
    rules: ['默认显示全部', '支持按时间/金额排序', '可导出 Excel'],
    links: ['b-order-detail'],
  },
  'b-order-detail': {
    key: 'b-order-detail',
    no: '18',
    title: '订单详情',
    role: 'designer',
    isTab: false,
    parentTab: 'b-orders',
    summary: 'B 端订单完整信息：进度 + 设计稿 + 物流。',
    modules: ['状态进度条(5 阶段)', '设计稿大图 + 工艺参数', '尺码分布表', '支付信息 + 物流', '底部操作(联系客服/复制单号)'],
    rules: ['进度实时更新', '设计稿可放大查看', '物流支持复制单号'],
    links: ['b-orders'],
  },
}

// 获取某角色的 tab 页列表
export function getTabsForRole(role) {
  return Object.values(PAGE_META)
    .filter(p => p.role === role && p.isTab)
    .sort((a, b) => a.no.localeCompare(b.no))
}

// 获取某角色的所有页面
export function getPagesForRole(role) {
  return Object.values(PAGE_META)
    .filter(p => p.role === role)
    .sort((a, b) => a.no.localeCompare(b.no))
}
